### ISSUE TITLE
Painting is broken

### ISSUE THREAD

**Issue by gena** [openearth/painting#8]

**Comment by SiggyF** [comment]
The `el` that is passed during creation of the drawing is recreated since the upgrade to vue 2.0. 
http://vuejs.org/v2/api/#el  

This gives issues in these constructs in the code:
- https://github.com/openearth/painting/blob/a0415e203ec95be86149e3091ef234976462c435/app/scripts/webgl.js#L197
- https://github.com/openearth/painting/blob/a0415e203ec95be86149e3091ef234976462c435/app/scripts/graphics.js#L120

In the current setup construction of the `map` creates `layers`, layers create `canvas` objects. The Vue instances that are generated dynamically replace the canvas objects.

**Comment by SiggyF** [comment]
And `pointer-event` is set to `none` for images. Which does not help.

**Comment by SiggyF** [comment]
Fixed in 6ff1bd
